### ISSUE TITLE
1.24a 草的生成异常

### ISSUE THREAD

**Issue by pame123-pame** [AmalaNever/MineFantasyWorld#1]
我在使用熔炉烧红砖和铁锭的时候，草经常生成在我的熔炉附近，令我不得不经常清理草，这让我非常烦躁，请问这应该怎么解决

**Comment by AmalaNever** [comment]
这个是因为你在熔炉烧东西时燃烧的煤炭或原木等产生了污染源——碳，碳污染源在天空中时，其下方具有草方块并且无草时会自动发挥其有效作用（温室效应）类似骨粉催熟（自行设计可用于农场催熟）。
解决办法：制作烟囱及过滤器，在熔炉四周任意位置放置烟囱，然后再烟囱的上方再放置过滤器，在并过滤器中加入任意树叶即可吸收由熔炉产生的碳污染，而不让他扩散到天空中。如果前期没有过滤器，可以选择铺原石等为地板，或者直接找个非草地的地方建家。后期搬家。

修正一下：是熔炉四周任意位置放置一个通风口，然后通风口的四周放置烟囱，另外，对于多个熔炉，你可以使用通风口连接到同一个烟囱，然后通过同一个过滤器过滤。同样的匠魂炉也一样会产生污染。如果你不会用可以看一看[我的mcbbs帖子](https://www.mcbbs.net/thread-967574-1-1.html)
还有[mod原文](https://www.curseforge.com/minecraft/mc-mods/pollution-of-the-realms)
