### ISSUE TITLE
wyvern energy core recipe not working 

### ISSUE THREAD

**Issue by BugsReporter9000** [AmalaNever/MineFantasyWorld#2]
hi .

the wyvern energy core recipe is not working , it accepts the materials but nothing in the output slot . 

thx

**Comment by AmalaNever** [comment]
Which version do you use? 
I will test it, then I will reply to you, and the next update will be solved. The next update should be within 4-5 days.

**Comment by AmalaNever** [comment]
> 
> 
> hi .
> 
> the wyvern energy core recipe is not working , it accepts the materials but nothing in the output slot .
> 
> thx

hello, I changed the recipe in 1.25(Why change, not fix, because I think this recipe is too simple)

**Comment by BugsReporter9000** [comment]
thanks , maybe the NBT tag is the problem with the battery or something .
