### ISSUE TITLE
开了服务器跟同学联机，但是进不去，显示timed out

### ISSUE THREAD

**Issue by yuxincao1283** [AmalaNever/MineFantasyWorld#3]
和朋友联机，但是进不去，log里有parsing error 然后进不去之前有 network dispacher exception

**Comment by AmalaNever** [comment]
非纯净forge端服务器，如mo端，cat端请自行添加：RandomPatches（下次更新加入）
https://www.curseforge.com/minecraft/mc-mods/randompatches
